package tardis.implementation.evosuite;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import jbse.mem.Clause;

/**
 * A work item produced by the Evosuite performer and 
 * consumed by the JBSE performer. It encapsulates a 
 * {@link TestCase}. It is immutable.
 * 
 * @author Pietro Braione
 */
public final class EvosuiteResult {
    /**
     * The name of the class
     * where the target method is defined.
     */
    private final String targetMethodClassName;
    
    /** The descriptor of the target method. */
    private final String targetMethodDescriptor;
    
    /** The name of the target method. */
    private final String targetMethodName;
    
    /** A {@link TestCase}. */
    private final TestCase testCase;
    
    /**
     * The post-frontier (final) path condition that
     * {@link #testCase} should cover, or {@code null}
     * if {@link #testCase} was generated by seeding.
     */
    private final List<Clause> pathConditionGenerating;
     
    /**
     * The depth starting from which the 
     * {@link #testCase} must be analyzed 
     * by the JBSE performer.
     */
    private final int startDepth;

    /**
     * Constructor.
     * 
     * @param targetMethodClassName A {@link String}, the name of the class
     *        where the target method is defined.
     * @param targetMethodDescriptor A {@link String}, the descriptor of the
     *        target method.
     * @param targetMethodName A {@link String}, the name of the target method.
     * @param pathConditionGenerating A {@link List}{@code <}{@link Clause}{@code >}, 
     *        a partial path condition. It can be null.
     * @param testCase A {@link TestCase}. Its execution should hit {@code targetMethod}
     *        and cover {@code pathConditionGenerating} when present.
     * @param startDepth A positive {@code int}, indicating the depth starting 
     *        from which the {@code testCase} must be analyzed by the JBSE performer.
     */
    public EvosuiteResult(String targetMethodClassName, String targetMethodDescriptor, String targetMethodName, List<Clause> pathConditionGenerating, TestCase testCase, int startDepth) {
        this.targetMethodClassName = targetMethodClassName;
        this.targetMethodDescriptor = targetMethodDescriptor;
        this.targetMethodName = targetMethodName;
        this.pathConditionGenerating = pathConditionGenerating == null ? null : Collections.unmodifiableList(new ArrayList<>(pathConditionGenerating));
        this.testCase = testCase;
        this.startDepth = startDepth;
    }

    /**
     * Constructor. Equivalent to {@link #EvosuiteResult(String, String, String, List<Clause>, TestCase, int) EvosuiteResult}{@code (targetMethod.get(0), targetMethod.get(1), targetMethod.get(2), null, testCase, startDepth)}.
     * 
     * @param targetMethod A {@link List}{@code <}{@link String}{@code >} that
     *        must have (at least) length 3.
     * @param testCase A {@link TestCase}. Its execution should hit {@code targetMethod}.
     * @param startDepth A positive {@code int}, indicating the depth starting 
     *        from which the {@code testCase} must be analyzed by the JBSE performer.
     */
    public EvosuiteResult(List<String> targetMethod, TestCase testCase, int startDepth) {
        this(targetMethod.get(0), targetMethod.get(1), targetMethod.get(2), null, testCase, startDepth);
    }

    /**
     * Returns the name of the class
     * where the target method is defined.
     * 
     * @return A {@link String}.
     */
    public String getTargetMethodClassName() {
        return this.targetMethodClassName;
    }

    /**
     * Returns the descriptor of the target method.
     * 
     * @return A {@link String}.
     */
    public String getTargetMethodDescriptor() {
        return this.targetMethodDescriptor;
    }

    /**
     * Returns the name of the target method.
     * 
     * @return A {@link String}.
     */
    public String getTargetMethodName() {
        return this.targetMethodName;
    }

    /**
     * Gets the signature of the target method.
     *
     * @return {@link #getTargetMethodClassName() getTargetMethodClassName}{@code () + ":" + }{@link #getTargetMethodDescriptor() getTargetMethodDescriptor}{@code () + ":" + }{@link #getTargetMethodName() getTargetMethodName}{@code ()}.
     */
    public String getTargetMethodSignature() {
    	return this.targetMethodClassName + ":" + this.targetMethodDescriptor + ":" + this.targetMethodName;
    }
    
    /**
     * Gets the path condition to cover which the {@link TestCase}
     * was generated.
     * 
     * @return a {@link List}{@code <}{@link Clause}{@code >}, or
     *         {@code null} if the {@link TestCase} was generated
     *         by seeding.
     */
    public List<Clause> getPathConditionGenerating() {
    	return this.pathConditionGenerating;
    }
    
    /**
     * Returns the {@link TestCase}.
     * 
     * @return A {@link TestCase}.
     */
    public TestCase getTestCase() {
        return this.testCase;
    }

    /**
     * Returns the depth starting 
     * from which the {@link #getTestCase() test case} 
     * must be analyzed by the JBSE performer.
     * 
     * @return An {@code int}.
     */
    public int getStartDepth() {
        return this.startDepth;
    }
}
